In [1]:
import tensorflow as tf
tf.__version__
tf.InteractiveSession() #TensorFlow behave almost imperatively

In [2]:
'''Imperative vs. Declarative Programming
'''
a = 1
b = 10
c = a + b   #Above code is a imperative as the machine perform a premitive addition between registers
'''
In a declarative system, a computer program is a high-level description of the computation that is to 
be performed. It does not instruct the computer exactly how to perform the computation
'''
a = tf.constant(1)
b = tf.constant(10)
c = a + b   #computation of adding two values together to create a new tensor
c           #it's a symbolic tensor (specifies the computation of adding two values together to create a new tensor)
c.eval()    #The actual computation will executed here

11

In [3]:
'''Initializing Constants'''
tf.zeros(2)             #reference to the desired tensor rather than the value of the tensor itself
tf.zeros(2).eval()      #evaluated value of the TensorFlow tensor is itself a Python numpy.ndarray object

tf.zeros(2).eval()      #Rank 1
tf.zeros((2,3)).eval()  #Rank 2
tf.ones((2,3)).eval()   
tf.ones((2,3,4)).eval() #Rank 3

tf.one_hot(2,3).eval()

tf.fill((2,3), value=5).eval()  #Filling tensors with 5 values

array([[5, 5, 5],
       [5, 5, 5]])

In [4]:
a = tf.constant(4)   #shouldn’t allow to change during the program execution
a.eval()

4

In [5]:
'''Sampling Random Tensors
more common to initialize tensors with random values. The most common way to do this is to sample each 
entry in the tensor from a random distribution. tf.random_normal allows for each entry in a tensor of 
specified shape to be sampled from a Normal distribution of specified mean and standard deviation
'''
tf.random_normal((2,3), mean=0, stddev=1).eval()    #Sampling a tensor with random Normal entries
'''
ML systems often make use of very large tensors that often have tens of millions of parameters. 
When we sample tens of millions of random values from the Normal distribution, it becomes  almost certain 
that some sampled values will be far from the mean. Such large samples can lead to numerical instability
it’s common to sample using tf.truncated_normal() instead of tf.random_normal()
'''
tf.truncated_normal((2,3), mean=0, stddev=1).eval()
'''
This function behaves the same as tf.random_normal() in terms of API, but drops and resamples all 
values more than 2 standard deviations from the mean

tf.random_uniform() behaves like tf.random_normal() except for the fact that random values are sampled 
from the Uniform distribution over a specified range
'''
tf.random_uniform((2,3), minval=-2, maxval=2).eval()

array([[-0.8276429 ,  1.5379848 , -0.9254217 ],
       [-0.08302164,  0.06432581, -0.04164839]], dtype=float32)

In [6]:
'''Tensor Addition and Scaling
TensorFlow makes use of Python’s operator overloading to make basic tensor arithmetic straightforward 
with standard Python operators
'''
a = tf.ones((2, 4, 5))
b = tf.truncated_normal((2, 4, 5), mean=1, stddev=1)
print("a:\n{}\n\nb:\n{}".format(a.eval(), b.eval()))

a+b
(a+b).eval()
(a*b).eval()
(2 * a).eval()

a:
[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]

b:
[[[ 2.5018222   0.39927334 -0.24483514  0.83463013  1.9613609 ]
  [-0.01510251  0.2295559   1.2271612   2.902155    0.1708582 ]
  [ 1.0894966   0.20701575  1.1862502   2.0226169   1.0524418 ]
  [ 1.9034389   0.9991687   1.8431818   1.6664019   0.7937262 ]]

 [[-0.5030118   1.3431244   1.0479171   0.7657201   0.43795526]
  [ 0.13085628  0.39882034  1.8522594   0.09540546  1.4336762 ]
  [-0.26118505 -0.88090825 -0.03742373 -0.30683827  1.9568762 ]
  [ 0.78635764 -0.43927348  2.2229838   1.2021183   0.7607702 ]]]


array([[[2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.]],

       [[2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.]]], dtype=float32)

In [7]:
'''multiplying two tensors get elementwise multiplication and not matrix multiplication'''
c = tf.fill((2,3), 2)
d = tf.fill((2,3), 5)
(c/d).eval()

array([[0.4, 0.4, 0.4],
       [0.4, 0.4, 0.4]])

In [8]:
'''Matrix Operations'''
tf.eye(5, dtype=tf.float32).eval()  #Identity Matrix

r = tf.range(1, 5, 1.)      #Vector 1->4, step 1
r.eval()                    #Rank 1
d = tf.diag(r)              #diagonal matrix with ascending values along the diagonal 
d.eval()
d.shape

#Transpose
a = tf.ones((3,4))
a.eval()
tf.matrix_transpose(a).eval()

a.shape
a.get_shape()

#Multiplication
tf.matmul(tf.ones((2, 3)), tf.ones((3, 4))).eval()
tf.matmul(a, d).eval()
tf.matmul(d, a).eval()      #Exception


ValueError: Dimensions must be equal, but are 4 and 3 for 'MatMul_2' (op: 'MatMul') with input shapes: [4,4], [3,4].

In [9]:
'''Tensor Shape Manipulations
tensors are just collections of numbers written in memory
'''
a.eval()
tf.reshape(a, (4, 3)).eval()
tf.reshape(tf.eye(4), (8,2)).eval()     #Rank 1
tf.reshape(tf.eye(4), (2,4,2)).eval()   #Rank 2 
tf.reshape(tf.eye(4), (2,2,4)).eval()
'''
It's convenient to perform simpler shape manipulations using functions-
-tf.expand_dims or tf.squeeze
tf.expand_dims adds an extra dimension to a tensor of size 1. It’s useful for increasing the rank of a 
tensor by one (for example, when converting a rank-1 vector into a rank-2 row vector or column vector). 
tf.squeeze, on the other hand, removes all dimensions of size 1 from a tensor. It’s a useful way to 
convert a row or column vector into a flat vector
'''
a = tf.ones(2)
a.eval()
a.shape
tf.expand_dims(a, 0).eval()
tf.expand_dims(a, 0).get_shape()
b = tf.expand_dims(a, 1)
b.eval()
b.get_shape()
tf.squeeze(b).eval()
tf.squeeze(b).shape

TensorShape([Dimension(2)])

In [10]:
'''Broadcasting
allow for conveniences like adding a vector to every row of a matrix
'''
a = tf.ones((2, 2))
a.eval()
#b = tf.range(0, 2, 1)   #TensorFlow doesn’t perform implicit type casting, will throw exception
b = tf.range(0, 2, 1, dtype = tf.float32) #need to set dtype explicitly
b.eval()
(a+b).eval()            #b is added to every row: Broadcasting

array([[1., 2.],
       [1., 2.]], dtype=float32)

In [11]:
'''Graphs
Any computation in TensorFlow is represented as an instance of a tf.Graph object.
Such a graph consists of a set of instances of tf.Tensor objects and tf.Operation objects. 
When a tf.Graph is not explicitly specified, TensorFlow adds tensors and operations to a hidden global 
tf.Graph instance.
'''
tf.get_default_graph()  #Getting the default TensorFlow graph

In [12]:
'''Sessions
Session object acts as an interface to the external TensorFlow computation mechanism, 
and allows us to run parts of the computation graph
A tf.Session() object stores the context under which a computation is performed. 
tf.InteractiveSession() to set up an environment for all TensorFlow computations. This call creats 
hidden global context for all computations performed. Used tf.Tensor.eval() to execute declaratively 
specified computations. This call is evaluated in context of this hidden global tf.Session
'''
sess = tf.Session()
a = tf.diag(tf.range(1, 3, .5))
b = tf.matmul(a, tf.matrix_transpose(a))    #adds the operation to a graph of computations
sess.run(b)             #Running a computation within a session
b.eval(session=sess)    #uses context of sess instead of the hidden global session
                        #just syntactic sugar for calling sess.run(b)

array([[1.  , 0.  , 0.  , 0.  ],
       [0.  , 2.25, 0.  , 0.  ],
       [0.  , 0.  , 4.  , 0.  ],
       [0.  , 0.  , 0.  , 6.25]], dtype=float32)

In [13]:
'''Variables
The tf.Variable() class provides a wrapper around tensors that allows for stateful computations.
The variable objects serve as holders for tensors
'''
a = tf.Variable(tf.eye(3))
a
tf.rank(a).eval()       #Rank 2
a.eval()                #Evaluating an uninitialized variable fails
'''
The evaluation fails since variables have to be explicitly initialized. The easiest way to
initialize all variables is to invoke tf.global_variables_initializer
'''
sess = tf.Session()
sess.run(tf.global_variables_initializer())
a.eval(sess)
'''Assigning Values'''
a.assign(tf.zeros((2,2)))           #Shape can't be changed
a.assign(tf.zeros((3,3)))           #No effect
sess.run(a.assign(tf.zeros((3,3)))) #Will update
a.eval(sess)
'''
The shape of the variable is fixed upon initialization and must be preserved with updates. 
tf.assign is itself a part of the underlying global tf.Graph instance. This allows TensorFlow
programs to update their internal state every time they are run.
'''

Instructions for updating:
Colocations handled automatically by placer.


FailedPreconditionError: Attempting to use uninitialized value Variable
	 [[{{node _retval_Variable_0_0}}]]

In [14]:
tf.zeros((2,2)).eval()
tf.rank(tf.zeros((2,2))).eval()
tf.zeros((3,3)).eval()
tf.rank(tf.zeros((3,3))).eval()

2

In [15]:
a = tf.constant("Hello")
b = tf.constant(" World")
ab = a + b
with tf.Session() as sess:
    res = sess.run(ab)
print(res)


b'Hello World'
